name: macOS build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{matrix.compiler}} ${{matrix.build_type}}
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        compiler:
          # - /usr/bin/g++
          - /usr/bin/clang++
        build_type: [Debug]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure build
        working-directory: .
        run: |
          cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

      - name: Build
        working-directory: .
        run: cmake --build build -j 2

      - name: Run test
        working-directory: ./build
        run: ctest -j 2
